[package]
name = "bevy_symbios"
version = "0.3.0"
edition = "2024"
authors = ["Janus"]
description = "Bevy integration for the Symbios L-System ecosystem."
license = "MIT"
readme = "README.md"
repository = "https://github.com/TheJanusStream/bevy_symbios"
keywords = ["lsystem", "procedural", "generative", "simulation"]
categories = ["simulation", "game-development", "mathematics"]

[features]
default = []
physics = ["dep:avian3d"]
egui = ["dep:bevy_egui"]
robot = ["dep:symbios-robot", "physics"]

[dependencies]
bevy = "0.18"
symbios = "1.4"
symbios-turtle-3d = { path = "../symbios-turtle-3d" }
symbios-robot = { path = "../symbios-robot", optional = true }
bevy_egui = { version = "0.39", optional = true }

[dependencies.avian3d]
git = "https://github.com/avianphysics/avian"
branch = "main"
optional = true

[dev-dependencies]
glam = "0.30.10"
avian3d = { git = "https://github.com/avianphysics/avian", branch = "main" }
